<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Prospect;

/**
 * EncounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncounterRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Count all encounters with a prospect
     * 
     * @param Prospect $prospect
     * @return int
     */
    public function getEncounterCount(Prospect $prospect)
    {
        $query = $this->_em->createQuery('
            SELECT COUNT(e)
            FROM AppBundle:Encounter e
            WHERE e.prospect = :prospect
        ')
         ->setParameter('prospect', $prospect)
        ;
        
        return $query->getSingleScalarResult();
    }
    
}
