<?php

namespace AppBundle\Repository;

/**
 * EncounterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncounterRepository extends \Doctrine\ORM\EntityRepository
{
}
