<?php

namespace AppBundle\Repository;

/**
 * RedFlagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedFlagRepository extends \Doctrine\ORM\EntityRepository
{
}
