<?php

namespace AppBundle\Repository;

/**
 * ZodiacRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZodiacRepository extends \Doctrine\ORM\EntityRepository
{
}
