   
fos_user:
#    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

    # locale: routes duplicated in my UserBundle for locale addition
    resource: "@UserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}/
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
# locale : add locale detection prefix to all annotation routes in AppBundle
app_bundle:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/
    requirements:
        _locale: en|fr
  
# locale: redirecting the root path "/" to route "home_index"
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: home_index
        permanent: true