imports:
#    - { resource: '@ApplicationSonataUserBundle/Resources/config/security.yml' }

security:
    acl:
        connection: default
    
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: 
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
        SONATA: 
            # if you are using acl then this line must be commented
            #- ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT  

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # custom firewall for the admin area of the URL        
        admin:            
            pattern: /admin(.*) 
            form_login:                
                provider:       fos_userbundle
                csrf_provider:  security.csrf.token_manager
                login_path:     /admin/login                
                use_forward:    false                
                check_path:     /admin/login_check                
                failure_path:   null            
            logout:                
                path: /admin/logout            
            anonymous: true 
        
        # defaut login area for standard users 
        # This firewall is used to handle the public login area
        # This part is handled by the FOS User Bundle
        main:            
            pattern:     .*   
            form_login:                
                provider:       fos_userbundle
                csrf_provider:  security.csrf.token_manager
                login_path:     /login                
                use_forward:    false                
                check_path:     /login_check  
                
                # Route par défaut après login
                default_target_path: /
                
                failure_path:   null            
            logout:
                path: /logout
            anonymous: ~
            switch_user: true
        
        

    access_control:
#        - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
                        
        - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY } 

        # USERS
        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }         
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        
        # ADMIN
        # Custom access control for the admin area of the URL 
        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/admin/login-check$, role: IS_AUTHENTICATED_ANONYMOUSLY }        
        
        # Secured part of the site        
        # This config requires being logged for the whole site and having the admin role for the admin part.        
        # Change these rules to adapt them to your needs        
        - { path: ^/admin, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        
        - { path: ^/.*, role: [ROLE_USER] }
