services:    
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    
    # Captcha form override
    app.registration.form.type:
        class: AppBundle\Form\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags: 
            - { name: form.type, alias: appbundle_user_registration }
    
    # EventSubscriber to redirect the user from registration to home if already logged in        
    app_user.subscriber.fos_user:
        class: AppBundle\EventSubscriber\FOSUserSubscriber
        arguments:
            - "@router"
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_subscriber }
            
    app.cachephoto_listener:
        class: AppBundle\EventListener\CachePhotoListener
        arguments: 
            - "@liip_imagine.cache.manager"
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }
            
    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['@router','%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }

    prospect_manager:
        class: AppBundle\DependencyInjection\Managers\ProspectManager
        arguments: 
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            
    photo_manager:
        class: AppBundle\DependencyInjection\Managers\PhotoManager
        arguments:            
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            
    default_manager:
        class: AppBundle\DependencyInjection\Managers\DefaultManager
        arguments: 
            - '@doctrine.orm.entity_manager'

    
#    redirection_after_login:
#        class: AppBundle\Handler\RedirectionAfterLogin
#        arguments: ['@router']