services:
    app.registration.form.type:
        class: AppBundle\Form\RegistrationType
        arguments: [%fos_user.model.user.class%]
        tags: 
            - { name: form.type, alias: appbundle_user_registration }
