<?php

namespace AppBundle\Entity\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationshipRankRepository extends \Doctrine\ORM\EntityRepository
{
}
