<?php
namespace AppBundle\EventListener;

use Doctrine\ORM\Event\LifecycleEventArgs;
use AppBundle\Entity\Photo;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Description of CachePhotoListener
 *
 * @author Norman
 */
class CachePhotoListener 
{
    protected $cacheManager;
    protected $request;
    
    public function __construct($cacheManager, RequestStack $request_stack) 
    {
        $this->cacheManager = $cacheManager;
        $this->request = $request_stack->getCurrentRequest();
    }
    
    // Case : update photo (crop or different photo)
    public function postUpdate(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();        
        
        if ($entity instanceof Photo) {
            // Remove all the cached images for that user
            // They are regenerated by the liip bundle afterwards
            $this->cacheManager->remove($entity->userPath());
        }
    }
    
    // Case : remove photo
    public function preRemove(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
//        $filter = 'thumb_prospect_250';
        
        $filters = array('thumb_prospect_250', 'thumb_prospect_175');
        
        foreach($filters as $filter){
            if ($entity instanceof Photo) {
                // Added check if the thumb exists
                // when a previous postUpdate deleted the whole cache folder without regenerating the thumbs
                $expectedCachePath = $this->cacheManager->getBrowserPath($entity->getPath(), $filter);            

                if (file_exists($expectedCachePath)) {
                    $this->cacheManager->resolve($this->request, $entity->getPath(), $filter);
                    $this->cacheManager->remove($entity->getPath());
                }
            }
        }
    }
}
