<?php
namespace AppBundle\EventListener;

use Doctrine\ORM\Event\LifecycleEventArgs;
use AppBundle\Entity\Photo;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Description of CachePhotoListener
 *
 * @author Norman
 */
class CachePhotoListener 
{
    protected $cacheManager;
    protected $request;
    
    public function __construct($cacheManager, RequestStack $request_stack) 
    {
        $this->cacheManager = $cacheManager;
        $this->request = $request_stack->getCurrentRequest();
    }
    
    // Case : update photo (crop or different photo)
    public function postUpdate(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();        
        
        if ($entity instanceof Photo) {
            // Remove all the cached images for that user
            // They are regenerated by the liip bundle afterwards
            $this->cacheManager->remove($entity->userPath());
        }
    }
    
    public function preRemove(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
        
        $filters = array('thumb_prospect_250', 'thumb_prospect_175');
        
        foreach($filters as $filter){
            if ($entity instanceof Photo) {
                // when a previous postUpdate deleted the whole cache folder without regenerating the thumbs           
                $cacheExists = $this->cacheManager->isStored($entity->getPath(), $filter);  // isStored returns boolean         

                if ($cacheExists) {
                    $this->cacheManager->resolve($entity->getPath(), $filter);
                    $this->cacheManager->remove($entity->getPath());
                }
            }
        }
    }
}
