# Sonata Admin services
services:
    admin.prospect:
        class: AppBundle\Admin\ProspectAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Prospect, label: Prospect }
        arguments: [null, AppBundle\Entity\Prospect, SonataAdminBundle:CRUD]


#    sonata.admin.prospect:
#        class: AppBundle\Admin\ProspectAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Prospect" }
#        arguments:
#            - ~
#            - AppBundle\Entity\Prospect
#            - ~
#        calls:
#            - [ setTranslationDomain, [AppBundle]]
