# Sonata Admin services
services:
    admin.prospects:
        class: playerManager\WelcomeBundle\Admin\ProspectsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Prospects, label: Prospects }
        arguments: [null, playerManager\WelcomeBundle\Entity\Prospects, SonataAdminBundle:CRUD]


#    sonata.admin.prospects:
#        class: playerManager\WelcomeBundle\Admin\ProspectsAdmin
#        tags:
#            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Prospects" }
#        arguments:
#            - ~
#            - playerManager\WelcomeBundle\Entity\Prospects
#            - ~
#        calls:
#            - [ setTranslationDomain, [playerManagerWelcomeBundle]]
